package ru.neginskiy.tm.endpoint;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.FaultAction;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.2.7
 * 2019-02-06T15:37:45.924+03:00
 * Generated source version: 3.2.7
 *
 */
@WebService(targetNamespace = "http://endpoint.tm.neginskiy.ru/", name = "DataEndpoint")
@XmlSeeAlso({ObjectFactory.class})
public interface DataEndpoint {

    @WebMethod
    @Action(input = "http://endpoint.tm.neginskiy.ru/DataEndpoint/saveDataBinRequest", output = "http://endpoint.tm.neginskiy.ru/DataEndpoint/saveDataBinResponse", fault = {@FaultAction(className = UncorrectSessionException_Exception.class, value = "http://endpoint.tm.neginskiy.ru/DataEndpoint/saveDataBin/Fault/UncorrectSessionException")})
    @RequestWrapper(localName = "saveDataBin", targetNamespace = "http://endpoint.tm.neginskiy.ru/", className = "ru.neginskiy.tm.endpoint.SaveDataBin")
    @ResponseWrapper(localName = "saveDataBinResponse", targetNamespace = "http://endpoint.tm.neginskiy.ru/", className = "ru.neginskiy.tm.endpoint.SaveDataBinResponse")
    public void saveDataBin(
        @WebParam(name = "session", targetNamespace = "")
        ru.neginskiy.tm.endpoint.Session session,
        @WebParam(name = "userId", targetNamespace = "")
        java.lang.String userId
    ) throws UncorrectSessionException_Exception;

    @WebMethod
    @Action(input = "http://endpoint.tm.neginskiy.ru/DataEndpoint/loadDataBinRequest", output = "http://endpoint.tm.neginskiy.ru/DataEndpoint/loadDataBinResponse", fault = {@FaultAction(className = UncorrectSessionException_Exception.class, value = "http://endpoint.tm.neginskiy.ru/DataEndpoint/loadDataBin/Fault/UncorrectSessionException")})
    @RequestWrapper(localName = "loadDataBin", targetNamespace = "http://endpoint.tm.neginskiy.ru/", className = "ru.neginskiy.tm.endpoint.LoadDataBin")
    @ResponseWrapper(localName = "loadDataBinResponse", targetNamespace = "http://endpoint.tm.neginskiy.ru/", className = "ru.neginskiy.tm.endpoint.LoadDataBinResponse")
    public void loadDataBin(
        @WebParam(name = "session", targetNamespace = "")
        ru.neginskiy.tm.endpoint.Session session,
        @WebParam(name = "userId", targetNamespace = "")
        java.lang.String userId
    ) throws UncorrectSessionException_Exception;

    @WebMethod
    @Action(input = "http://endpoint.tm.neginskiy.ru/DataEndpoint/loadJsonBinRequest", output = "http://endpoint.tm.neginskiy.ru/DataEndpoint/loadJsonBinResponse", fault = {@FaultAction(className = UncorrectSessionException_Exception.class, value = "http://endpoint.tm.neginskiy.ru/DataEndpoint/loadJsonBin/Fault/UncorrectSessionException")})
    @RequestWrapper(localName = "loadJsonBin", targetNamespace = "http://endpoint.tm.neginskiy.ru/", className = "ru.neginskiy.tm.endpoint.LoadJsonBin")
    @ResponseWrapper(localName = "loadJsonBinResponse", targetNamespace = "http://endpoint.tm.neginskiy.ru/", className = "ru.neginskiy.tm.endpoint.LoadJsonBinResponse")
    public void loadJsonBin(
        @WebParam(name = "session", targetNamespace = "")
        ru.neginskiy.tm.endpoint.Session session,
        @WebParam(name = "userId", targetNamespace = "")
        java.lang.String userId
    ) throws UncorrectSessionException_Exception;

    @WebMethod
    @Action(input = "http://endpoint.tm.neginskiy.ru/DataEndpoint/saveJsonBinRequest", output = "http://endpoint.tm.neginskiy.ru/DataEndpoint/saveJsonBinResponse", fault = {@FaultAction(className = UncorrectSessionException_Exception.class, value = "http://endpoint.tm.neginskiy.ru/DataEndpoint/saveJsonBin/Fault/UncorrectSessionException")})
    @RequestWrapper(localName = "saveJsonBin", targetNamespace = "http://endpoint.tm.neginskiy.ru/", className = "ru.neginskiy.tm.endpoint.SaveJsonBin")
    @ResponseWrapper(localName = "saveJsonBinResponse", targetNamespace = "http://endpoint.tm.neginskiy.ru/", className = "ru.neginskiy.tm.endpoint.SaveJsonBinResponse")
    public void saveJsonBin(
        @WebParam(name = "session", targetNamespace = "")
        ru.neginskiy.tm.endpoint.Session session,
        @WebParam(name = "userId", targetNamespace = "")
        java.lang.String userId
    ) throws UncorrectSessionException_Exception;
}
