package ru.neginskiy.tm.endpoint;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.2.7
 * 2019-01-22T20:01:25.146+03:00
 * Generated source version: 3.2.7
 *
 */
@WebService(targetNamespace = "http://endpoint.tm.neginskiy.ru/", name = "UserEndpoint")
@XmlSeeAlso({ObjectFactory.class})
public interface UserEndpoint {

    @WebMethod
    @Action(input = "http://endpoint.tm.neginskiy.ru/UserEndpoint/userGetAllRequest", output = "http://endpoint.tm.neginskiy.ru/UserEndpoint/userGetAllResponse")
    @RequestWrapper(localName = "userGetAll", targetNamespace = "http://endpoint.tm.neginskiy.ru/", className = "ru.neginskiy.tm.endpoint.UserGetAll")
    @ResponseWrapper(localName = "userGetAllResponse", targetNamespace = "http://endpoint.tm.neginskiy.ru/", className = "ru.neginskiy.tm.endpoint.UserGetAllResponse")
    @WebResult(name = "return", targetNamespace = "")
    public java.util.List<ru.neginskiy.tm.endpoint.User> userGetAll();

    @WebMethod
    @Action(input = "http://endpoint.tm.neginskiy.ru/UserEndpoint/userMergeRequest", output = "http://endpoint.tm.neginskiy.ru/UserEndpoint/userMergeResponse")
    @RequestWrapper(localName = "userMerge", targetNamespace = "http://endpoint.tm.neginskiy.ru/", className = "ru.neginskiy.tm.endpoint.UserMerge")
    @ResponseWrapper(localName = "userMergeResponse", targetNamespace = "http://endpoint.tm.neginskiy.ru/", className = "ru.neginskiy.tm.endpoint.UserMergeResponse")
    public void userMerge(
        @WebParam(name = "user", targetNamespace = "")
        ru.neginskiy.tm.endpoint.User user
    );

    @WebMethod
    @Action(input = "http://endpoint.tm.neginskiy.ru/UserEndpoint/userGetByIdRequest", output = "http://endpoint.tm.neginskiy.ru/UserEndpoint/userGetByIdResponse")
    @RequestWrapper(localName = "userGetById", targetNamespace = "http://endpoint.tm.neginskiy.ru/", className = "ru.neginskiy.tm.endpoint.UserGetById")
    @ResponseWrapper(localName = "userGetByIdResponse", targetNamespace = "http://endpoint.tm.neginskiy.ru/", className = "ru.neginskiy.tm.endpoint.UserGetByIdResponse")
    @WebResult(name = "return", targetNamespace = "")
    public ru.neginskiy.tm.endpoint.User userGetById(
        @WebParam(name = "id", targetNamespace = "")
        java.lang.String id
    );

    @WebMethod
    @Action(input = "http://endpoint.tm.neginskiy.ru/UserEndpoint/userDeleteRequest", output = "http://endpoint.tm.neginskiy.ru/UserEndpoint/userDeleteResponse")
    @RequestWrapper(localName = "userDelete", targetNamespace = "http://endpoint.tm.neginskiy.ru/", className = "ru.neginskiy.tm.endpoint.UserDelete")
    @ResponseWrapper(localName = "userDeleteResponse", targetNamespace = "http://endpoint.tm.neginskiy.ru/", className = "ru.neginskiy.tm.endpoint.UserDeleteResponse")
    @WebResult(name = "return", targetNamespace = "")
    public ru.neginskiy.tm.endpoint.User userDelete(
        @WebParam(name = "id", targetNamespace = "")
        java.lang.String id
    );
}
